---
driver:
  name: dokken
  privileged: true # allows systemd services to start
  chef_image: cincproject/cinc
  chef_version: <%= ENV.fetch('CHEF_VERSION', 18) %>

provisioner:
  name: dokken
  product_name: cinc
  chef_binary: /opt/cinc/bin/cinc-client
  deprecations_as_errors: true
  multiple_converge: 2
  enforce_idempotency: true

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  # @see https://github.com/chef-cookbooks/testing_examples/blob/main/kitchen.dokken.yml
  # @see https://hub.docker.com/u/dokken
  - name: debian-11
    driver:
      image: dokken/debian-11
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get upgrade -y
  - name: debian-12
    driver:
      image: dokken/debian-12
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get upgrade -y

suites:
  - name: default
    run_list:
      - recipe[tor-ng::default]
    attributes:
      tor-ng:
        torrc:
          onion_services:
            testservice: { port: "80 127.0.0.1:80" }
